NTSTATUS REG_OpenLDNTVDM(DWORD dwAccess, PHKEY phKey);
NTSTATUS REG_QueryDWORD(HKEY hKey, LPWSTR lpKey, PDWORD pdwResult);
NTSTATUS REG_SetDWORD(HKEY hKey, LPWSTR lpKey, DWORD dwData);
VOID REG_CloseKey(HKEY hKey);
